#
# Copyright (C) 2017-2026 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Configuration and authentication for Dremio Cloud."""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

logger = logging.getLogger(__name__)

DEFAULT_CONFIG_PATH = Path.home() / ".config" / "dremioai" / "config.yaml"
DEFAULT_URI = "https://api.dremio.cloud"


class OAuthConfig(BaseModel):
    """OAuth token state stored in the config file."""

    access_token: str | None = None
    refresh_token: str | None = None
    client_id: str | None = None


class DrsConfig(BaseModel):
    uri: str = DEFAULT_URI
    pat: str
    project_id: str
    oauth: OAuthConfig | None = None


def load_config(
    config_path: Path | None = None,
    *,
    cli_token: str | None = None,
    cli_project_id: str | None = None,
    cli_uri: str | None = None,
) -> DrsConfig:
    """Load config with resolution order: CLI args > env vars > config file > defaults.

    Authentication priority:
      1. --token CLI arg
      2. DREMIO_TOKEN / DREMIO_PAT env var
      3. Config file oauth.access_token (from OAuth login)
      4. Config file pat/token field
    """
    # -- Config file (lowest priority) --
    file_values: dict[str, Any] = {}
    oauth_config: OAuthConfig | None = None
    path = config_path or DEFAULT_CONFIG_PATH
    if path.exists():
        with path.open() as f:
            raw = yaml.safe_load(f) or {}
        file_values = {
            "uri": raw.get("uri", raw.get("endpoint")),
            "pat": raw.get("pat", raw.get("token")),
            "project_id": raw.get("project_id", raw.get("projectId")),
        }
        file_values = {k: v for k, v in file_values.items() if v is not None}

        # Load OAuth section if present
        if "oauth" in raw and isinstance(raw["oauth"], dict):
            oauth_config = OAuthConfig(
                access_token=raw["oauth"].get("access_token"),
                refresh_token=raw["oauth"].get("refresh_token"),
                client_id=raw["oauth"].get("client_id"),
            )
            # Use OAuth access_token as the PAT if no explicit PAT is set
            if oauth_config.access_token and "pat" not in file_values:
                file_values["pat"] = oauth_config.access_token

    # -- Env vars (override file) --
    env_values: dict[str, Any] = {}
    if v := os.environ.get("DREMIO_URI"):
        env_values["uri"] = v
    if (v := os.environ.get("DREMIO_TOKEN")) or (v := os.environ.get("DREMIO_PAT")):
        env_values["pat"] = v
    if v := os.environ.get("DREMIO_PROJECT_ID"):
        env_values["project_id"] = v

    # -- Merge: defaults < file < env --
    merged: dict[str, Any] = {"uri": DEFAULT_URI}
    merged.update(file_values)
    merged.update(env_values)

    # -- CLI args (highest priority, override everything) --
    if cli_uri:
        merged["uri"] = cli_uri
    if cli_project_id:
        merged["project_id"] = cli_project_id
    if cli_token:
        merged["pat"] = cli_token

    config = DrsConfig(**merged)
    config.oauth = oauth_config
    return config


def save_oauth_tokens(
    access_token: str,
    refresh_token: str | None,
    client_id: str,
    config_path: Path | None = None,
) -> None:
    """Write OAuth tokens to the config file (preserves other fields)."""
    path = config_path or DEFAULT_CONFIG_PATH
    path.parent.mkdir(parents=True, exist_ok=True)

    # Read existing config
    raw: dict[str, Any] = {}
    if path.exists():
        with path.open() as f:
            raw = yaml.safe_load(f) or {}

    # Update oauth section
    raw["oauth"] = {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "client_id": client_id,
    }

    # Write back
    header = "# Dremio CLI config — generated by 'dremio setup' / 'dremio auth login'\n"
    path.write_text(header + yaml.dump(raw, default_flow_style=False, sort_keys=False))
    path.chmod(0o600)
    logger.debug("OAuth tokens saved to %s", path)


def clear_oauth_tokens(config_path: Path | None = None) -> None:
    """Remove OAuth tokens from the config file."""
    path = config_path or DEFAULT_CONFIG_PATH
    if not path.exists():
        return

    with path.open() as f:
        raw = yaml.safe_load(f) or {}

    if "oauth" in raw:
        del raw["oauth"]
        header = "# Dremio CLI config — generated by 'dremio setup' / 'dremio auth login'\n"
        path.write_text(header + yaml.dump(raw, default_flow_style=False, sort_keys=False))
        path.chmod(0o600)


def get_config_path_from_context(config_path: Path | None = None) -> Path:
    """Return the effective config path."""
    return config_path or DEFAULT_CONFIG_PATH
